name: 'Kubescape Action'
author: 'rbalashevich'
description: 'GitHub action to scan given k8s manifests using kubescape by ARMO'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  ksversion:
    description: 'kubescape release to use'
    required: true
    default: 'v2.0.158'
  path:
    description: 'File or directory to run scan on'
    required: false
    default: '.'
  threshold:
    description: 'Parameter to set the threshold (optional)'
    required: false
    default: '20'
  format:
    description: 'Output format (optional)'
    # Supported formats: "pretty-printer","json","junit","prometheus","pdf" (default "pretty-printer")
    required: false
    default: 'pretty-printer'
  context:
    description: 'K8s cluster context (kube-context) to run scan on'
    required: false
    default: ''    
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: DOCKER_BUILDKIT=1
  args:
    - ${{ inputs.ksversion }}
    - ${{ inputs.path }}
    - ${{ inputs.threshold }}
    - ${{ inputs.format }}
    - ${{ inputs.context }}


    

    
  
    
