name: Test2
on:
  workflow_dispatch:
jobs:
  scan-cluster:
   runs-on: ubuntu-latest
   steps:  
    - name: Checkout
      uses: actions/checkout@v3    
    - name: Write kubeconfig to file
      run: echo "${{ secrets.KUBECONFIG_CONTENT }}" > mykubeconfig
    - name: Verify kubeconfig substitution and set context
      id: verifyandset
      run: |
        var=$(kubectl config current-context)
        echo $KUBECONFIG
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        kubectl config current-context
        kubectl get pod -A
        echo "::set-output name=KUBE_CONTEXT::$var"
      env: 
        KUBECONFIG: mykubeconfig
    - name: Scan cluster
      uses: otomato-gh/kubescape-action@main
      with:
          ksversion: 'v2.0.155'
          format:  'json'
          context: ${{ steps.verifyandset.outputs.KUBE_CONTEXT }}
      env: 
        KUBECONFIG: mykubeconfig
    - name: Retrieve Scan Results via File Upload
      if: always() 
      uses: actions/upload-artifact@v3
      with:
        name: scan-results
        path: results.*    
        
        
